### ISSUE TITLE
tracking

### ISSUE THREAD

**Issue by Jialin1227** [Jialin1227/EDCI338#1]
- [ ] Wow and Wonder 1

- [ ] Wow and Wonder 2

- [ ] Wow and Wonder 3

- [ ] Wow and Wonder 4

- [ ] Wow and Wonder 5

- [ ] Wow and Wonder 6

- [ ] Wow and Wonder 7

- [ ] Showcase 1

- [ ] Major Project

- [ ] Celebration of Learning
